//! Resumable background sharpness-indexing job (H16b).
//!
//! [`run_index`] is the single entry point. It:
//!
//! 1. Queries all photos where `sharpness IS NULL` (unscored).
//! 2. Resolves each photo to its cached ~2048px preview path via the catalog resolver.
//! 3. Loads the preview bytes with the thumbnail pipeline (`preview_bytes`), which ensures
//!    the preview is at 1024–2048px — the minimum resolution needed to see micro-blur.
//!    **Never uses the 256px thumbnail**: micro-blur is invisible there (see design doc).
//! 4. Decodes the JPEG, scores it with [`crate::sharpness::score_image`] (`method='tile'`).
//! 5. Writes `(sharpness, sharpness_method)` back to the catalog via
//!    `Catalog::set_sharpness`.
//! 6. Emits `sharpness:progress {done, total}` Tauri events after each processed photo.
//! 7. Checks the `abort` flag after each photo — stops cleanly when tripped, leaving
//!    unscored rows for the next run (resume-safe because `sharpness IS NULL` is the queue).
//!
//! ## The Preview, Not the Thumbnail
//!
//! The 256px thumbnail cannot show micro-blur: a back-focused eye looks sharp at that size.
//! We score on the ~1024–2048px cached preview. The preview is generated by the same decode
//! pipeline as the loupe (`thumbnails::preview_bytes`), cached on disk keyed by path+mtime,
//! so a subsequent loupe open is a free cache hit.
//!
//! ## Parallelism
//!
//! Preview loading + decode + scoring is CPU+I/O bound. We use rayon for the parallel decode
//! pass, the same pattern as `plugins/faces/indexer.rs` — resolve + load + score in parallel,
//! then collect results back to a sequential loop for SQLite writes (which require `&Connection`,
//! not `Send`).
//!
//! ## Resume-safety
//!
//! The indexer's "queue" is implicit: `SELECT id FROM photos WHERE sharpness IS NULL`. Writing
//! the score atomically to `photos` (one UPDATE per photo) means a crash mid-run leaves the
//! remaining rows as IS NULL → the next run picks them up automatically. No separate queue table.
//!
//! ## Score-on-import path
//!
//! Newly imported photos are scored for free via the I7b analyzer hook in
//! `thumbnails::register_analyzer`. The hook receives the freshly decoded image from the
//! thumbnail/preview/warm-all pipeline and calls [`score_and_store`], so scoring rides the
//! existing decode instead of re-reading the file. The background `index_sharpness` job
//! handles the backfill for photos imported before this code was deployed.

use std::path::Path;
use std::sync::atomic::{AtomicBool, Ordering};

use rusqlite::Connection;
use serde::Serialize;

/// The `sharpness_method` value written by the tiled scorer (H16b). The region-aware
/// methods (`face` / `afpoint`, H16c) come from [`crate::sharpness_regions::Method`].
pub const METHOD_TILE: &str = "tile";

/// Progress event payload for `sharpness:progress`.
#[derive(Debug, Clone, Serialize)]
pub struct SharpnessProgress {
    pub done: usize,
    pub total: usize,
}

/// How an index run ended.
#[derive(Debug, Clone, Default, Serialize)]
pub struct IndexOutcome {
    /// Photos actually scored in this run.
    pub done: usize,
    /// Photos that were unscored when the run started (total queue length).
    pub total: usize,
    /// Photos whose preview could not be generated (unreadable/undecodable file).
    pub failed: usize,
    /// Photos skipped because no reachable copy exists right now (offline/NAS).
    pub offline: usize,
    /// True when the run stopped early because the abort flag tripped.
    pub aborted: bool,
}

/// Run the sharpness-indexing job.
///
/// - `conn`            — a *secondary* catalog connection (no lock contention with the UI).
/// - `resolve_path_fn` — closure that, given a photo_id, returns `Ok(Some(path))` when a
///                       reachable copy is found, `Ok(None)` when offline, `Err` on failure.
///                       In production this calls `catalog.resolve_photo_path(id)`.
/// - `regions_fn`      — closure that, given a photo_id, returns its [`RegionInputs`] (face
///                       boxes + AF point) read from the catalog. Called **sequentially**
///                       (the connection is not `Sync`), so it may touch the DB freely.
///                       Returns `RegionInputs::default()` (→ tile method) when nothing is
///                       available.
/// - `preview_fn`      — closure that, given `&Path`, returns JPEG bytes at ~1024–2048px.
///                       In production this calls `thumbnails::preview_bytes`.
/// - `score_fn`        — closure that, given raw JPEG bytes and the photo's [`RegionInputs`],
///                       returns the sharpness score **and the method** used
///                       (`tile` / `face` / `afpoint`). It applies the region-aware priority
///                       chain (H16c): score inside face boxes when present, else at the AF
///                       point, else tiles. In production this is [`score_jpeg_regions`].
///                       Must be `Send + Sync` because it is called from rayon worker threads.
/// - `abort`           — shared abort flag; checked after each batch.
/// - `emit_progress`   — callback receiving `SharpnessProgress` after each processed photo.
///
/// Returns an `IndexOutcome`.
pub fn run_index<ResolveFn, RegionsFn, PreviewFn, ScoreFn, EmitFn>(
    conn: &Connection,
    resolve_path_fn: ResolveFn,
    regions_fn: RegionsFn,
    preview_fn: &PreviewFn,
    score_fn: &ScoreFn,
    abort: &AtomicBool,
    mut emit_progress: EmitFn,
) -> Result<IndexOutcome, String>
where
    ResolveFn: Fn(i64) -> Result<Option<std::path::PathBuf>, String>,
    RegionsFn: Fn(i64) -> RegionInputs,
    PreviewFn: Fn(&Path) -> Result<Vec<u8>, String> + Sync,
    ScoreFn: Fn(&[u8], &RegionInputs) -> Option<(f64, &'static str)> + Sync,
    EmitFn: FnMut(SharpnessProgress),
{
    use rayon::prelude::*;

    // Collect all unscored photo ids. This is the implicit queue.
    let queue = load_unscored(conn)?;
    let total = queue.len();
    let mut outcome = IndexOutcome { total, ..IndexOutcome::default() };
    let mut done = 0usize;

    // Process in chunks so each chunk's results are written before the next starts,
    // keeping memory bounded and giving the abort flag a chance to trip at each boundary.
    const CHUNK: usize = 64;
    for chunk in queue.chunks(CHUNK) {
        if abort.load(Ordering::Relaxed) {
            outcome.aborted = true;
            break;
        }

        // ── Step 1: sequential resolve + region-gather pass ──────────────────────
        // Collect (photo_id, path, regions) for photos that are currently reachable. The
        // region inputs (face boxes / AF point) are read from the catalog *here*, in the
        // sequential pass, because the rusqlite `Connection` is not `Sync` and cannot be
        // touched from the parallel scoring workers below.
        let mut to_score: Vec<(i64, std::path::PathBuf, RegionInputs)> =
            Vec::with_capacity(chunk.len());
        for &photo_id in chunk {
            match resolve_path_fn(photo_id) {
                Ok(Some(p)) => {
                    let regions = regions_fn(photo_id);
                    to_score.push((photo_id, p, regions));
                }
                Ok(None) => {
                    // Photo is offline; leave unscored for next run.
                    eprintln!(
                        "sharpness_index: photo {photo_id} is offline — skipping for this run"
                    );
                    outcome.offline += 1;
                }
                Err(e) => {
                    eprintln!("sharpness_index: resolve failed for photo {photo_id}: {e}");
                    outcome.offline += 1;
                }
            }
        }

        if to_score.is_empty() {
            continue;
        }

        // ── Step 2: parallel preview + score pass ─────────────────────────────────
        // No conn access here — pure I/O + pixel math over the pre-gathered regions.
        enum ScoreResult {
            Scored(f64, &'static str),
            PreviewError(String),
        }

        let results: Vec<(i64, std::path::PathBuf, ScoreResult)> = to_score
            .par_iter()
            .map(|(photo_id, path, regions)| {
                let jpeg = match preview_fn(path) {
                    Ok(b) => b,
                    Err(e) => {
                        return (*photo_id, path.clone(), ScoreResult::PreviewError(e));
                    }
                };
                let result = match score_fn(&jpeg, regions) {
                    Some((s, method)) => ScoreResult::Scored(s, method),
                    None => ScoreResult::PreviewError("image decode failed".to_string()),
                };
                (*photo_id, path.clone(), result)
            })
            .collect();

        // ── Step 3: sequential write pass ────────────────────────────────────────
        for (photo_id, _path, result) in results {
            match result {
                ScoreResult::PreviewError(e) => {
                    eprintln!("sharpness_index: preview/decode failed for photo {photo_id}: {e}");
                    outcome.failed += 1;
                    // Leave sharpness IS NULL so the next run retries.
                }
                ScoreResult::Scored(score, method) => {
                    write_sharpness(conn, photo_id, score, method)?;
                    done += 1;
                    emit_progress(SharpnessProgress { done, total });
                }
            }

            if abort.load(Ordering::Relaxed) {
                outcome.aborted = true;
                break;
            }
        }

        if outcome.aborted {
            break;
        }
    }

    outcome.done = done;
    Ok(outcome)
}

/// Score JPEG bytes with the tiled sharpness scorer. Returns `None` when the image
/// cannot be decoded (unreadable / unsupported format). Used both by the indexer
/// and by the I7b analyzer hook.
///
/// Decoding is done here (not in `sharpness.rs`) because `sharpness.rs` is a pure
/// pixel-math function and does not import the `image` crate's JPEG decoder.
pub fn score_jpeg(jpeg: &[u8]) -> Option<f64> {
    let img = image::load_from_memory(jpeg).ok()?;
    Some(crate::sharpness::score_image(&img))
}

/// The per-photo region inputs the priority chain (H16c) chooses between: detected face
/// boxes and the camera AF point. Both are optional; whichever is present and non-empty
/// (faces first) decides the method. Fetched by the caller from the catalog (faces from
/// `faces__faces` under the `faces` feature; AF from `photo_metadata`), so this stays a
/// pure decision over already-gathered data — no catalog access, no feature gate.
#[derive(Debug, Clone, Default)]
pub struct RegionInputs {
    /// Detected face boxes on the oriented image (`faces__faces.bbox`). Empty when the
    /// `faces` feature is off or the photo has no faces.
    pub face_boxes: Vec<crate::sharpness_regions::NormBox>,
    /// Normalized AF point on the oriented image, parsed from the Sony `FocusLocation`
    /// makernote. `None` when the photo carries no usable AF point.
    pub af_point: Option<(f32, f32)>,
}

/// Score JPEG preview bytes with the region-aware priority chain (H16c):
///
/// 1. **face** — if any face box scores (non-degenerate, on-image), use the sharpest box.
/// 2. **afpoint** — else if an AF point is present, score its neighbourhood.
/// 3. **tile** — else the tiled top-percentile baseline.
///
/// Each earlier tier only wins when it actually produces a score; a face box entirely
/// off-image or an AF point that yields a degenerate patch falls through to the next tier,
/// so the method is honest about what was measured. Returns `None` only when the JPEG
/// cannot be decoded at all.
pub fn score_jpeg_regions(jpeg: &[u8], regions: &RegionInputs) -> Option<(f64, &'static str)> {
    let img = image::load_from_memory(jpeg).ok()?;
    Some(score_image_regions(&img, regions))
}

/// Apply the region-aware priority chain to an already-decoded image (the I7b analyzer
/// hook holds one, so it scores without re-decoding). Same tiers as [`score_jpeg_regions`].
pub fn score_image_regions(
    img: &image::DynamicImage,
    regions: &RegionInputs,
) -> (f64, &'static str) {
    use crate::sharpness_regions::{score_af_point, score_faces, Method, AF_PATCH_FRAC};
    let gray = img.to_luma8();

    // Tier 1: faces.
    if !regions.face_boxes.is_empty() {
        if let Some(s) = score_faces(&gray, &regions.face_boxes) {
            return (s, Method::Face.as_str());
        }
    }
    // Tier 2: AF point.
    if let Some((nx, ny)) = regions.af_point {
        if let Some(s) = score_af_point(&gray, nx, ny, AF_PATCH_FRAC) {
            return (s, Method::AfPoint.as_str());
        }
    }
    // Tier 3: tiled baseline.
    (crate::sharpness::score_gray(&gray), Method::Tile.as_str())
}

/// Read a photo's AF point from the catalog, parsed and oriented onto the preview frame.
///
/// The scan stored the raw Sony `FocusLocation` makernote and the EXIF orientation code as
/// `photo_metadata` entries (see `metadata::enrich_af_points`). This resolves both and hands
/// them to [`crate::sharpness_regions::parse_focus_location`], returning the normalized AF
/// point on the oriented image, or `None` when the photo has no usable AF data (non-Sony
/// file, older import before this field was captured, malformed value).
pub fn photo_af_point(conn: &Connection, photo_id: i64) -> Option<(f32, f32)> {
    use crate::metadata::{AF_ORIENTATION_KEY, AF_POINT_KEY};
    use rusqlite::OptionalExtension as _;

    let loc: Option<String> = conn
        .query_row(
            "SELECT value FROM photo_metadata WHERE photo_id = ?1 AND key = ?2 LIMIT 1",
            rusqlite::params![photo_id, AF_POINT_KEY],
            |r| r.get(0),
        )
        .optional()
        .ok()
        .flatten();
    let loc = loc?;

    let orientation: u16 = conn
        .query_row(
            "SELECT value FROM photo_metadata WHERE photo_id = ?1 AND key = ?2 LIMIT 1",
            rusqlite::params![photo_id, AF_ORIENTATION_KEY],
            |r| r.get::<_, String>(0),
        )
        .optional()
        .ok()
        .flatten()
        .and_then(|s| s.trim().parse().ok())
        .unwrap_or(1);

    crate::sharpness_regions::parse_focus_location(&loc, orientation)
}

/// Load all photo IDs where `sharpness IS NULL`, ordered by `id` for stable resumption.
fn load_unscored(conn: &Connection) -> Result<Vec<i64>, String> {
    let mut stmt = conn
        .prepare("SELECT id FROM photos WHERE sharpness IS NULL ORDER BY id ASC")
        .map_err(|e| e.to_string())?;
    let rows = stmt
        .query_map([], |r| r.get::<_, i64>(0))
        .map_err(|e| e.to_string())?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| e.to_string())?;
    Ok(rows)
}

/// Write a sharpness score + method to the catalog for one photo. Caller holds the
/// secondary catalog connection; there is no mutex around this call.
pub fn write_sharpness(
    conn: &Connection,
    photo_id: i64,
    score: f64,
    method: &str,
) -> Result<(), String> {
    conn.execute(
        "UPDATE photos SET sharpness = ?1, sharpness_method = ?2 WHERE id = ?3",
        rusqlite::params![score, method, photo_id],
    )
    .map_err(|e| e.to_string())?;
    Ok(())
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use rusqlite::Connection;
    use std::sync::atomic::AtomicBool;
    use std::sync::Arc;

    fn mem_conn() -> Connection {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(
            "PRAGMA foreign_keys = ON;
             CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
             CREATE TABLE IF NOT EXISTS photos (
                 id               INTEGER PRIMARY KEY,
                 uuid             TEXT NOT NULL DEFAULT '',
                 path             TEXT NOT NULL DEFAULT '',
                 sharpness        REAL,
                 sharpness_method TEXT
             );",
        )
        .unwrap();
        conn
    }

    fn insert_photo(conn: &Connection, id: i64) {
        conn.execute(
            "INSERT INTO photos (id) VALUES (?1)",
            rusqlite::params![id],
        )
        .unwrap();
    }

    fn get_sharpness(conn: &Connection, id: i64) -> Option<(f64, String)> {
        conn.query_row(
            "SELECT sharpness, sharpness_method FROM photos WHERE id = ?1",
            [id],
            |r| Ok((r.get::<_, f64>(0)?, r.get::<_, String>(1)?)),
        )
        .ok()
    }

    fn unscored_count(conn: &Connection) -> usize {
        conn.query_row(
            "SELECT COUNT(*) FROM photos WHERE sharpness IS NULL",
            [],
            |r| r.get::<_, i64>(0),
        )
        .unwrap_or(0) as usize
    }

    // A simple in-memory score_fn that returns a fixed value + method (no JPEG decode).
    fn dummy_score(_jpeg: &[u8], _r: &RegionInputs) -> Option<(f64, &'static str)> {
        Some((42.0, METHOD_TILE))
    }

    // No-region gatherer for tests that don't exercise the priority chain.
    fn no_regions(_id: i64) -> RegionInputs {
        RegionInputs::default()
    }

    #[test]
    fn run_index_scores_all_photos() {
        let conn = mem_conn();
        for id in 1i64..=3 {
            insert_photo(&conn, id);
        }
        let abort = Arc::new(AtomicBool::new(false));
        let mut events = Vec::new();

        let outcome = run_index(
            &conn,
            |id| Ok(Some(std::path::PathBuf::from(format!("/fake/{id}.jpg")))),
            no_regions,
            &|_path| Ok(vec![0xFFu8, 0xD8, 0xFF, 0xE0]),
            &dummy_score,
            &abort,
            |p| events.push(p),
        )
        .unwrap();

        assert_eq!(outcome.total, 3);
        assert_eq!(outcome.done, 3);
        assert_eq!(outcome.offline, 0);
        assert_eq!(outcome.failed, 0);
        assert!(!outcome.aborted);
        assert_eq!(unscored_count(&conn), 0, "all photos must be scored");
        assert_eq!(events.len(), 3);
        assert_eq!(events.last().unwrap().done, 3);

        // Verify the written values.
        for id in 1i64..=3 {
            let (score, method) = get_sharpness(&conn, id).expect("sharpness must be written");
            assert_eq!(score, 42.0);
            assert_eq!(method, METHOD_TILE);
        }
    }

    #[test]
    fn run_index_skips_already_scored() {
        use std::sync::atomic::{AtomicUsize, Ordering as AOrdering};
        let conn = mem_conn();
        for id in 1i64..=3 {
            insert_photo(&conn, id);
        }
        // Pre-score photo 2 (simulating a prior completed run).
        conn.execute(
            "UPDATE photos SET sharpness = 10.0, sharpness_method = 'tile' WHERE id = 2",
            [],
        )
        .unwrap();

        let abort = Arc::new(AtomicBool::new(false));
        let score_calls = Arc::new(AtomicUsize::new(0));
        let score_calls_c = score_calls.clone();

        let outcome = run_index(
            &conn,
            |id| Ok(Some(std::path::PathBuf::from(format!("/fake/{id}.jpg")))),
            no_regions,
            &|_path| Ok(vec![0xFFu8, 0xD8, 0xFF, 0xE0]),
            &move |_jpeg: &[u8], _r: &RegionInputs| {
                score_calls_c.fetch_add(1, AOrdering::Relaxed);
                Some((99.0, METHOD_TILE))
            },
            &abort,
            |_| {},
        )
        .unwrap();

        // Only photos 1 and 3 were unscored.
        assert_eq!(outcome.total, 2, "total counts only unscored photos");
        assert_eq!(outcome.done, 2);
        assert_eq!(
            score_calls.load(AOrdering::Relaxed),
            2,
            "already-scored photo must be skipped"
        );
        // Photo 2's score must be untouched.
        let (s2, _) = get_sharpness(&conn, 2).unwrap();
        assert_eq!(s2, 10.0, "pre-existing score must not be overwritten");
    }

    #[test]
    fn run_index_resumes_after_partial_run() {
        let conn = mem_conn();
        for id in 1i64..=4 {
            insert_photo(&conn, id);
        }
        let abort = Arc::new(AtomicBool::new(false));
        abort.store(true, Ordering::Relaxed); // trip immediately

        let outcome1 = run_index(
            &conn,
            |id| Ok(Some(std::path::PathBuf::from(format!("/fake/{id}.jpg")))),
            no_regions,
            &|_path| Ok(vec![0xFFu8, 0xD8, 0xFF, 0xE0]),
            &dummy_score,
            &abort,
            |_| {},
        )
        .unwrap();

        // All photos still unscored because abort was tripped before any chunk ran.
        assert!(outcome1.aborted);
        // Even if done == 0 (abort tripped before first chunk), resume should work.
        let remaining_before = unscored_count(&conn);
        assert_eq!(remaining_before, 4, "abort before first chunk: nothing scored");

        // Second run (no abort): scores everything left over.
        let abort2 = Arc::new(AtomicBool::new(false));
        let outcome2 = run_index(
            &conn,
            |id| Ok(Some(std::path::PathBuf::from(format!("/fake/{id}.jpg")))),
            no_regions,
            &|_path| Ok(vec![0xFFu8, 0xD8, 0xFF, 0xE0]),
            &dummy_score,
            &abort2,
            |_| {},
        )
        .unwrap();

        assert_eq!(outcome2.total, remaining_before);
        assert_eq!(outcome2.done, remaining_before);
        assert_eq!(unscored_count(&conn), 0);
    }

    #[test]
    fn run_index_counts_preview_failures() {
        let conn = mem_conn();
        for id in 1i64..=2 {
            insert_photo(&conn, id);
        }
        let abort = Arc::new(AtomicBool::new(false));

        let outcome = run_index(
            &conn,
            |id| Ok(Some(std::path::PathBuf::from(format!("/fake/{id}.jpg")))),
            no_regions,
            &|path| {
                // Photo 1's preview fails.
                if path.ends_with("1.jpg") {
                    Err("unreadable".to_string())
                } else {
                    Ok(vec![0xFFu8, 0xD8, 0xFF, 0xE0])
                }
            },
            &dummy_score,
            &abort,
            |_| {},
        )
        .unwrap();

        assert_eq!(outcome.done, 1);
        assert_eq!(outcome.failed, 1);
        // Photo 1 must remain unscored (stays in the implicit queue for retry).
        assert_eq!(unscored_count(&conn), 1, "failed photo must remain unscored");
    }

    #[test]
    fn run_index_counts_decode_failures() {
        let conn = mem_conn();
        for id in 1i64..=2 {
            insert_photo(&conn, id);
        }
        let abort = Arc::new(AtomicBool::new(false));

        let outcome = run_index(
            &conn,
            |id| Ok(Some(std::path::PathBuf::from(format!("/fake/{id}.jpg")))),
            no_regions,
            &|_path| Ok(vec![0xFFu8, 0xD8, 0xFF, 0xE0]),
            // score_fn for photo 1 fails (simulate undecodable preview).
            &|_jpeg: &[u8], _r: &RegionInputs| None,
            &abort,
            |_| {},
        )
        .unwrap();

        assert_eq!(outcome.done, 0);
        assert_eq!(outcome.failed, 2);
        assert_eq!(unscored_count(&conn), 2, "decode-failed photos remain unscored");
    }

    #[test]
    fn run_index_offline_does_not_advance_done() {
        let conn = mem_conn();
        for id in 1i64..=2 {
            insert_photo(&conn, id);
        }
        let abort = Arc::new(AtomicBool::new(false));

        let outcome = run_index(
            &conn,
            |id| {
                if id == 1 {
                    Ok(None) // offline
                } else {
                    Ok(Some(std::path::PathBuf::from(format!("/fake/{id}.jpg"))))
                }
            },
            no_regions,
            &|_path| Ok(vec![0xFFu8, 0xD8, 0xFF, 0xE0]),
            &dummy_score,
            &abort,
            |_| {},
        )
        .unwrap();

        assert_eq!(outcome.done, 1);
        assert_eq!(outcome.total, 2);
        assert_eq!(outcome.offline, 1);
        // Photo 1 still unscored.
        assert_eq!(unscored_count(&conn), 1);
        assert!(get_sharpness(&conn, 2).is_some(), "reachable photo must be scored");
    }

    #[test]
    fn write_sharpness_roundtrip() {
        let conn = mem_conn();
        insert_photo(&conn, 42);
        write_sharpness(&conn, 42, 123.456, METHOD_TILE).unwrap();
        let (s, m) = get_sharpness(&conn, 42).unwrap();
        assert!((s - 123.456).abs() < 1e-9);
        assert_eq!(m, METHOD_TILE);
    }

    // ── H16c: region-aware priority chain ────────────────────────────────────────

    use crate::sharpness_regions::NormBox;
    use image::{GrayImage, Luma};

    /// Encode a grayscale image as JPEG bytes so `score_jpeg_regions` can decode it.
    fn jpeg_of(gray: &GrayImage) -> Vec<u8> {
        let dynimg = image::DynamicImage::ImageLuma8(gray.clone());
        let mut buf = std::io::Cursor::new(Vec::new());
        dynimg
            .write_to(&mut buf, image::ImageFormat::Jpeg)
            .unwrap();
        buf.into_inner()
    }

    fn sharp(w: u32, h: u32) -> GrayImage {
        GrayImage::from_fn(w, h, |x, y| {
            let on = ((x / 4) + (y / 4)) % 2 == 0;
            Luma([if on { 255u8 } else { 0u8 }])
        })
    }

    #[test]
    fn score_jpeg_regions_picks_face_when_boxes_present() {
        let jpeg = jpeg_of(&sharp(256, 256));
        let regions = RegionInputs {
            face_boxes: vec![NormBox { x: 0.3, y: 0.3, w: 0.3, h: 0.3 }],
            af_point: Some((0.5, 0.5)),
        };
        let (_score, method) = score_jpeg_regions(&jpeg, &regions).unwrap();
        assert_eq!(method, "face", "faces take priority over AF point");
    }

    #[test]
    fn score_jpeg_regions_falls_to_afpoint_without_faces() {
        let jpeg = jpeg_of(&sharp(256, 256));
        let regions = RegionInputs {
            face_boxes: vec![],
            af_point: Some((0.5, 0.5)),
        };
        let (_score, method) = score_jpeg_regions(&jpeg, &regions).unwrap();
        assert_eq!(method, "afpoint", "AF point used when no faces");
    }

    #[test]
    fn score_jpeg_regions_falls_to_tile_without_faces_or_af() {
        let jpeg = jpeg_of(&sharp(256, 256));
        let regions = RegionInputs::default();
        let (_score, method) = score_jpeg_regions(&jpeg, &regions).unwrap();
        assert_eq!(method, "tile", "tiles are the last resort");
    }

    #[test]
    fn score_jpeg_regions_face_box_offscreen_falls_through_to_af() {
        // A face box entirely off-image produces no score → must fall through to AF, not
        // wrongly claim method='face'.
        let jpeg = jpeg_of(&sharp(256, 256));
        let regions = RegionInputs {
            face_boxes: vec![NormBox { x: 3.0, y: 3.0, w: 0.5, h: 0.5 }],
            af_point: Some((0.5, 0.5)),
        };
        let (_score, method) = score_jpeg_regions(&jpeg, &regions).unwrap();
        assert_eq!(method, "afpoint", "degenerate face box falls through to AF");
    }

    #[test]
    fn score_jpeg_regions_bad_af_falls_through_to_tile() {
        // An out-of-range AF point produces no score → fall through to tiles.
        let jpeg = jpeg_of(&sharp(256, 256));
        let regions = RegionInputs {
            face_boxes: vec![],
            af_point: Some((1.5, 0.5)),
        };
        let (_score, method) = score_jpeg_regions(&jpeg, &regions).unwrap();
        assert_eq!(method, "tile", "unusable AF point falls through to tiles");
    }

    #[test]
    fn score_jpeg_regions_undecodable_is_none() {
        let regions = RegionInputs::default();
        assert!(score_jpeg_regions(&[0, 1, 2, 3], &regions).is_none());
    }

    #[test]
    fn run_index_writes_region_methods() {
        // End-to-end: the region inputs gathered in Step 1 (regions_fn) must flow into the
        // scorer and the resulting method must be persisted — not a hardcoded 'tile'.
        // Photo 1 gets a face box → face; photo 2 gets an AF point → afpoint; photo 3 gets
        // nothing → tile. The score_fn mirrors the real priority chain over its inputs.
        let conn = mem_conn();
        for id in 1i64..=3 {
            insert_photo(&conn, id);
        }
        let abort = Arc::new(AtomicBool::new(false));
        let outcome = run_index(
            &conn,
            |id| Ok(Some(std::path::PathBuf::from(format!("/fake/{id}.jpg")))),
            |id| match id {
                1 => RegionInputs {
                    face_boxes: vec![NormBox { x: 0.1, y: 0.1, w: 0.2, h: 0.2 }],
                    af_point: None,
                },
                2 => RegionInputs { face_boxes: vec![], af_point: Some((0.5, 0.5)) },
                _ => RegionInputs::default(),
            },
            &|_path| Ok(vec![0xFFu8, 0xD8, 0xFF, 0xE0]),
            &|_jpeg: &[u8], r: &RegionInputs| {
                if !r.face_boxes.is_empty() {
                    Some((7.0, "face"))
                } else if r.af_point.is_some() {
                    Some((3.0, "afpoint"))
                } else {
                    Some((1.0, METHOD_TILE))
                }
            },
            &abort,
            |_| {},
        )
        .unwrap();
        assert_eq!(outcome.done, 3);
        assert_eq!(get_sharpness(&conn, 1).unwrap().1, "face");
        assert_eq!(get_sharpness(&conn, 2).unwrap().1, "afpoint");
        assert_eq!(get_sharpness(&conn, 3).unwrap().1, "tile");
    }

    #[test]
    fn load_unscored_excludes_already_scored() {
        let conn = mem_conn();
        for id in 1i64..=5 {
            insert_photo(&conn, id);
        }
        write_sharpness(&conn, 2, 1.0, METHOD_TILE).unwrap();
        write_sharpness(&conn, 4, 2.0, METHOD_TILE).unwrap();

        let unscored = load_unscored(&conn).unwrap();
        assert_eq!(unscored, vec![1, 3, 5]);
    }
}
